### ISSUE TITLE
Dependencies on logDir and logFileNamePrefix during standalone module function testing

### ISSUE THREAD

**Issue by KevinAtAMD** [vmware-samples/vmware-architecture-migration-tool#1]
The following variables used in the Write-Log function located in the VAMT.psm1 PS module are not being set when functions are called standalone:
logDir
logFileNamePrefix

The function I am testing with is Initialize-VIServer, which then calls Write-Log, which has those two dependencies, so I get prompted for those values during testing of the execution.

I'm getting prompted each time multiple times in that function when it calls Write-Log when trying to call that Initialize-VIServer function from the VAMT.psm1 module. Down inside that call, it then makes calls to other functions in that module, which all work. BUT on the Write-Log cmdlet it has 2 parameters that are mandatory for the call, and those values are not passed in to the initialize function in this modular standalone use case, which leads the script to prompt for that log input both times.
Initialize function header:
function Initialize-VIServer {
    param(
        [Parameter(Mandatory)]
        [ValidateNotNullOrEmpty()]
        [String[]]$vCenters,
        [Parameter()]
        [PSCredential]$cred,
        [Parameter()]
        [String]$credentialDirectory
    )
Write-Log call from within the .psm1
function Write-Log {
    [CmdletBinding()]
    param(
.
.
[Parameter(Mandatory)]
[ValidateNotNullOrEmpty()]
[String]$logDir,
.
.
[Parameter(Mandatory)]
[ValidateNotNullOrEmpty()]
[String]$logFileNamePrefix,
Here is the output from the run after I fixed or worked around my other bugs, where I import the module and then call the function. You can see it prompt me each time it tries to write the log, because these 2 variables are missing:
logDir
logFileNamePrefix
There are many ways we could skin the cat, but in general that is really one of the more useful modular functions. I'm fine with whatever approach you want to use, but some that came to mind are that 1) we could add a default log location and prefix down in the call, 2) we could add a parameter to skip logging altogether, 3) we could remove mandatory from the arguments and then use their presense as the trigger not to log if they are null, etc. My inclination is to make logging optional, but let me know what you think. I've created a branch off main for testing this, so can try out fixes as needed, if you want to just direct me in what you feel is the right way.
PS C:\users\admin\test\vamt-tools> .\connect.ps1

cmdlet Write-Log at command pipeline position 1
Supply values for the following parameters:
logDir: C:\users\admin\test
logFileNamePrefix: test

cmdlet Write-Log at command pipeline position 1
Supply values for the following parameters:
logDir: C:\users\admin\test
logFileNamePrefix: test

cmdlet Write-Log at command pipeline position 1
Supply values for the following parameters:
logDir: C:\users\admin\test
logFileNamePrefix: test
[Info] 09/07/2022 11:40:38 - Saved new credential for 'vsphere.maas'. User: 'administrator@vsphere.local'

cmdlet Write-Log at command pipeline position 1
Supply values for the following parameters:
logDir: C:\users\admin\test
logFileNamePrefix: test
[Info] 09/07/2022 11:40:44 - Logging in to vCenter vsphere.maas with User: administrator@vsphere.local
Removing all snapshots in VAMT-Demo-Kevin

**Comment by austinbrowder** [comment]
This dependency has been resolved by https://github.com/vmware-samples/vmware-architecture-migration-tool/commit/1c046bca4d2eb54bd0a888a9c32c588b52d56b25.

If no path is passed to the write log function, logging to the filesystem will simply be skipped.

**Comment by KevinAtAMD** [comment]
Thanks @austinbrowder , I'll give this a test and close it if all is well.

**Comment by KevinAtAMD** [comment]
Looks good, thanks!
