### ISSUE TITLE
Add more retryable errors to script

### ISSUE THREAD

**Issue by KevinAtAMD** [vmware-samples/vmware-architecture-migration-tool#13]
### Is your feature request related to a problem? Please describe.

In the current vcenter test environment for vsphere 8 we are using with VMFS datastores, vcenter encounters the following error:

[Error] 03/21/2023 18:40:40 - VM move job for 'Test2' failed with errors:                                                                Caught excecption in migration job on line '148':                                                                                        3/21/2023 6:40:25 PM    Move-VM         The operation for the entity "Test2" failed with the following message: "Could not complete network copy for file /vmfs/volumes/640f46db-56785310-2b16-84160caa86ec/Test2/Test2_5.vmdk".

[20230321-171248_VMFSTransientFailure.zip](https://github.com/vmware-samples/vmware-architecture-migration-tool/files/11040995/20230321-171248_VMFSTransientFailure.zip)

There is also an error that looks to be retryable relative to tag state:

3/20/2023 2:36:48 PM Get-TagAssignment There was no endpoint listening at https://vsphere.maas/sdk that could accept the message. This is often caused by an incorrect address or SOAP action. See InnerException, if present, for more details. 3/20/2023 2:36:48 PM Get-TagAssignment Could not find TagCategory with name 'VAMT'. 3/20/2023 2:36:48 PM Get-TagAssignment TagCategory parameter: Could not find any of the objects specified by name. 3/20/2023 2:36:48 PM Get-Tag There was no endpoint listening at https://vsphere.maas/lookupservice/sdk that could accept the message. This is often caused by an incorrect address or SOAP action. See InnerException, if present, for more details. 3/20/2023 2:36:48 PM Get-Tag Could not find TagCategory with name 'VAMT'. 3/20/2023 2:36:48 PM Get-Tag TagCategory parameter: Could not find any of the objects specified by name. 3/20/2023 2:36:48 PM Get-Tag Tag with name 'complete' was not found using the specified filter(s). Caught excecption in migration job on line '799': Cannot bind argument to parameter 'Tag' because it is null.

[20230320-142245_TagNotFound.zip](https://github.com/vmware-samples/vmware-architecture-migration-tool/files/11041061/20230320-142245_TagNotFound.zip)

And this was one from a little while back that also had to do with invalid tag state:

[20230222-173117_InvalidTagState.zip](https://github.com/vmware-samples/vmware-architecture-migration-tool/files/11040994/20230222-173117_InvalidTagState.zip)

### Describe the solution you'd like

When this migration is ran again a second time for both of these errors, it always succeeds, so would like to add both of these to the list of retryable errors.

### Describe alternatives you've considered

Just running the script again is the current workaround.  But since we have the retry mechanism seems like a better approach.

### Additional context

I've added log file zips for each one to this issue

**Comment by austinbrowder** [comment]
These two ([20230321-171248_VMFSTransientFailure.zip](https://github.com/vmware-samples/vmware-architecture-migration-tool/files/11040995/20230321-171248_VMFSTransientFailure.zip) & [20230222-173117_InvalidTagState.zip](https://github.com/vmware-samples/vmware-architecture-migration-tool/files/11040994/20230222-173117_InvalidTagState.zip)) should be fixed by this commit:
https://github.com/vmware-samples/vmware-architecture-migration-tool/commit/fc65f2a37254ed14a1182d02c033ec4a495db151

This one ([20230222-173117_InvalidTagState.zip](https://github.com/vmware-samples/vmware-architecture-migration-tool/files/11040994/20230222-173117_InvalidTagState.zip)) should have been fixed by this commit where we reworked the logic to retry on null errors:
https://github.com/vmware-samples/vmware-architecture-migration-tool/commit/702661d25acf20ddf5c37efb0aaa80c0202670e1

Please pull latest and test.

**Comment by KevinAtAMD** [comment]
Verified the NULL tag state error is fixed from before.  Working on validating the other two retries in the VMFS test setup.

**Comment by KevinAtAMD** [comment]
OK, was able to reproduce the error around the VMFS and that retries worked. I'll go with the code review in the commit for the other error, since it is the same logic, just different error message, and close this one.

[Info] 03/22/2023 19:17:02 - Script run summary:
        Script start: '03/22/2023 16:29:36'
        Script runtime: 167 minutes
        Script completion: '03/22/2023 19:17:02'
        Total VM targets in migration run: 10
        Total VM jobs with retry attempts: 3
        VM migration jobs with final status 'Completed': 10
[Info] 03/22/2023 19:17:02 - Final report:

tgt_compute tgt_network job_result                      tgt_storage    tgt_folder       tag_state job_state src_vcenter   attempts tgt_v
                                                                                                                                   m
----------- ----------- ----------                      -----------    ----------       --------- --------- -----------   -------- -----
intel       VM Network  Successfully moved VM 'Test1'.  Datastore2 (2) VAMT-VersionTest complete  Completed vsphere8.maas 2        Test1
intel       VM Network  Successfully moved VM 'Test2'.  Datastore2 (2) VAMT-VersionTest complete  Completed vsphere8.maas 1        Test2
intel       VM Network  Successfully moved VM 'Test3'.  Datastore2 (2) VAMT-VersionTest complete  Completed vsphere8.maas 2        Test3
intel       VM Network  Successfully moved VM 'Test4'.  Datastore2 (2) VAMT-VersionTest complete  Completed vsphere8.maas 1        Test4
intel       VM Network  Successfully moved VM 'Test5'.  Datastore2 (2) VAMT-VersionTest complete  Completed vsphere8.maas 1        Test5
intel       VM Network  Successfully moved VM 'Test6'.  Datastore2 (2) VAMT-VersionTest complete  Completed vsphere8.maas 2        Test6
intel       VM Network  Successfully moved VM 'Test7'.  Datastore2 (2) VAMT-VersionTest complete  Completed vsphere8.maas 1        Test7
intel       VM Network  Successfully moved VM 'Test8'.  Datastore2 (2) VAMT-VersionTest complete  Completed vsphere8.maas 1        Test8
intel       VM Network  Successfully moved VM 'Test9'.  Datastore2 (2) VAMT-VersionTest complete  Completed vsphere8.maas 1        Test9
intel       VM Network  Successfully moved VM 'Test10'. Datastore2 (2) VAMT-VersionTest complete  Completed vsphere8.maas 1        Te...
