### ISSUE TITLE
Add counts to summary data at the end of the migration

### ISSUE THREAD

**Issue by KevinAtAMD** [vmware-samples/vmware-architecture-migration-tool#2]
During various larger scale VAMT testing runs using VMmark3 benchmark in 20 tile (380 VM) and 21 tile (399 VM) scenarios, we discovered that it would be useful to have the counts added to the summary data.

This is an example of the summary data that is sent out at the end:

[Info] 11/05/2022 00:38:12 - Script run summary:
        Script start: '11/04/2022 23:39:12'
        Script runtime: 58 minutes
        Script completion: '11/05/2022 00:38:12'
[Info] 11/05/2022 00:38:12 - Final report:

Would like to add something like:

Total VM targets in migration run: X
VMs successfully migrated: Y
VMs that failed migration: Z

**Comment by austinbrowder** [comment]
This has been addressed in the https://github.com/vmware-samples/vmware-architecture-migration-tool/tree/feature-multi_vc branch.
Please test.

**Comment by KevinAtAMD** [comment]
Thanks @austinbrowder.  I'll pull that branch and give it a shot, and if all is well then I'll close it out.

**Comment by KevinAtAMD** [comment]
Looks like we have the counts showing successfully now:

![image](https://user-images.githubusercontent.com/105498840/211212598-2777a376-cb4c-49cb-80e7-8e12b3515809.png)
