### ISSUE TITLE
Error seen during migration: "Detected invalid tag state" during OCI testing

### ISSUE THREAD

**Issue by KevinAtAMD** [vmware-samples/vmware-architecture-migration-tool#5]
### Describe the bug

This seems to be due to a transient error in VMware.

This is the error:
[Error] 02/22/2023 17:41:03 - VM move job for 'vm069' failed with errors:
Caught exception in migration job on line '57':
Detected invalid tag state '' on 'vm069'. This is likely the result of a concurent job running on the VM elsewhere.

### Reproduction steps

1. Migrate 100 VMs between the AMD and Intel cluster
2. Randomly see this error in what appears to be due to timing

### Expected behavior

Migration should succeed on all 100 VMs.

### Additional context

Logs can be found in the shared jumphost on OCI at: C:\Users\opc\Desktop\VAMT\vmware-architecture-migration-tool\vamt_runlogs\20230222-173117

**Comment by austinbrowder** [comment]
Logs attached
[20230222-173117_InvalidTagState.zip](https://github.com/vmware-samples/vmware-architecture-migration-tool/files/10944234/20230222-173117_InvalidTagState.zip)

**Comment by austinbrowder** [comment]
This is likely a load or resource related issue. Simply detecting this error and making it eligible for a retry with this commit:
https://github.com/vmware-samples/vmware-architecture-migration-tool/commit/1e1f76e2fb709b85acfedb1b4a57150b27f31d46

**Comment by KevinAtAMD** [comment]
Validated the retry logic is in for this with error message, closing issue.
