### ISSUE TITLE
MINOR bug: Error message says CSV file when input is a JSON

### ISSUE THREAD

**Issue by KevinAtAMD** [vmware-samples/vmware-architecture-migration-tool#6]
### Describe the bug

When testing out a migration, I accidentally used the same VM name in a JSON input file.  Error message is:

`[Error] 02/23/2023 08:11:29 - The following VM names were found more than once (vm200) in the inputs CSV file.
The following VM names were found more than once (vm200) in the inputs CSV file.
At C:\users\opc\Desktop\VAMT\vmware-architecture-migration-tool\VMwareArchitectureMigrationTool.ps1:354 char:5
+     throw $message
+     ~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (The following V...nputs CSV file.:String) [], RuntimeException
    + FullyQualifiedErrorId : The following VM names were found more than once (vm200) in the inputs CSV file.`
 

### Reproduction steps

1. Put invalid entry into JSON file
2. Attempt migration

### Expected behavior

Error message should probably just say "input VM list file" or something like that.

**Comment by austinbrowder** [comment]
fixed with https://github.com/vmware-samples/vmware-architecture-migration-tool/commit/c3d0a0016065a9747d71b5a96c3cddb9c97d34b1

**Comment by KevinAtAMD** [comment]
Verified by forcing same name and getting the following correct output, closing issue now

[Info] 03/22/2023 15:40:42 - VAMT Module has been imported and logging defaults have been loaded into module.
[Info] 03/22/2023 15:40:42 - Beginning inputs file validation.
[Error] 03/22/2023 15:40:42 - The following VM names were found more than once (NFStest1) in the inputs file.
The following VM names were found more than once (NFStest1) in the inputs file.
At C:\Users\admin\Test\AMT\VMwareArchitectureMigrationTool.ps1:371 char:5
+     throw $message
+     ~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (The following V...he inputs file.:String) [], RuntimeException
    + FullyQualifiedErrorId : The following VM names were found more than once (NFStest1) in the inputs file.
