### ISSUE TITLE
Add number of VM retries to migration summary

### ISSUE THREAD

**Issue by KevinAtAMD** [vmware-samples/vmware-architecture-migration-tool#7]
### Is your feature request related to a problem? Please describe.

Would be good to see whether there were any retries in the summary as well as in the detailed log listing.  For instance, when there is a retryable error as below:

`[Info] 02/23/2023 08:25:17 - New batch of moves: vm208, vm209, vm184, vm185, vm212
[Error] 02/23/2023 08:25:34 - VM move job for 'vm212' failed with errors:
[Warn] 02/23/2023 08:25:34 - Error is eligible to be re-tried. Setting retry status to try again later for 'vm212'.
[Info] 02/23/2023 08:25:34 - There are currently 19 moves in progress and 273 moves waiting to start.`

The summary will show the following when complete if the retry succeeded:
`[Info] 02/23/2023 09:16:52 - Script run summary:
       Script start: '02/23/2023 08:19:39'
       Script runtime: 57 minutes
       Script completion: '02/23/2023 09:16:52'
       Total VM targets in migration run: 300
       VM migration jobs with final status 'Completed': 300
[Info] 02/23/2023 09:16:52 - Final report:`

And the number of attempts is shown in the detailed logging:
`tgt_compute              tgt_network job_result                     tgt_storage   tgt_folder    tag_state job_state src_vcenter                                      attempts tgt_vm
-----------              ----------- ----------                     -----------   ----------    --------- --------- -----------                                      -------- ------
oci01-w01-consolidated01 VM Network  Successfully moved VM 'vm001'. vsanDatastore MigrationTest complete  Completed vcenter-wuovkm-sddc.sddc.iad.oci.oraclecloud.com 1        vm001
oci01-w01-consolidated01 VM Network  Successfully moved VM 'vm002'. vsanDatastore MigrationTest complete  Completed vcenter-wuovkm-sddc.sddc.iad.oci.oraclecloud.com 1        vm002`

For ease of visibility, would be good to see the number of VMs with retries.

### Describe the solution you'd like

Something like the following:

`[Info] 02/23/2023 09:16:52 - Script run summary:
       Script start: '02/23/2023 08:19:39'
       Script runtime: 57 minutes
       Script completion: '02/23/2023 09:16:52'
       Total VM targets in migration run: 300
       VM migration jobs with final status 'Completed': 300
       VMs with retries: 1
[Info] 02/23/2023 09:16:52 - Final report:`

### Describe alternatives you've considered

Thought about writing a separate parsing script to scrape the log for output metadata, but would be easier to do and see in the summary.

**Comment by austinbrowder** [comment]
added functionality via https://github.com/vmware-samples/vmware-architecture-migration-tool/commit/061c1e21bea5771d2410f98637c880d9e2ec7f71

**Comment by KevinAtAMD** [comment]
Verified add of this at https://github.com/vmware-samples/vmware-architecture-migration-tool/commit/061c1e21bea5771d2410f98637c880d9e2ec7f71
