### ISSUE TITLE
Add additional input parameters for tuning script

### ISSUE THREAD

**Issue by KevinAtAMD** [vmware-samples/vmware-architecture-migration-tool#8]
### Is your feature request related to a problem? Please describe.

Would like to be able to tune some more of the internal parameter knobs.  Note that the defaults below are fine as defaults, but would like to be able to tweak these for different environments:

$Script:vamtOsShutdownTimeout = 600 #seconds
$Script:vamtOsPowerOnTimeout = 900 #seconds
$jobControllerRefreshInterval = 15 #seconds

### Describe the solution you'd like

Add parameters for CLI like this one for the requested values: https://github.com/vmware-samples/vmware-architecture-migration-tool/blob/c03a2b896e49df5c8ff7d380547ced7dd5d6ddf1/VMwareArchitectureMigrationTool.ps1#L62 in for the variables shown.

**Comment by austinbrowder** [comment]
added functionality via https://github.com/vmware-samples/vmware-architecture-migration-tool/commit/7c589e4500200e17bd265d84a9ea00111057a9e7

**Comment by KevinAtAMD** [comment]
Verified new parameters at: https://github.com/vmware-samples/vmware-architecture-migration-tool/commit/7c589e4500200e17bd265d84a9ea00111057a9e7, will close this.
